# NUMPY

In [2]:
import numpy as np

In [3]:
from numpy import *
#CON ESTO NO TENDREMOS QUE ANTEPONER
#EL PREFIJO DE LA FUNCION DE NUMPY,
#NO ES RECOMENDABLE

In [5]:
L1=[1,2,3,4,5,6,7,8,9,10]#LISTA

In [6]:
#CONVIRTIENDO A ARRAY NumPy
X1=np.array(L1)
X1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#ARRAY NumPy CON NUMEROS DECIMALES
X2=np.array(L1,dtype='float32')
X2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## TIPOS DE DATOS
- bool
- int_, intc, intp, intB,int16,int32,int64
- uint8, unit16, uint32, unit64, son enteros sin signo
- float_, float16, float32, float64
- complex_, complex64, complex128

In [9]:
np.zeros((3,4))
#3 filas 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))
#3 filas 4 columnas

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.arange(1,10,dtype=np.float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [13]:
np.linspace(3.0,6.0,8)
#GENERA VALORES (INICIO,FINAL,CANTIDAD DE DATOS A GENERAR)
#TODOS TIENEN EL MISMO ESPACIO ENTRE ESOS DATOS

array([3.        , 3.42857143, 3.85714286, 4.28571429, 4.71428571,
       5.14285714, 5.57142857, 6.        ])

In [14]:
np.eye(5)
#GENERA UNA MATRIZ IDENTIDAD DE DIMENSIONES

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x=np.zeros((8,4))#8f 4c
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
x.reshape(4,8)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
xx=np.arange(24)
xx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
xx.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
xx.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [35]:
xxx=array([[1,2,3,4],[5,6,7,8]])
xxx

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
np.ravel(xxx)
#Modifica a la matriz original y retorna
#un arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
#variante de raven
xxx.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
#transponer
xxx.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
#genera mas elementos dentro de un vector
#pero cambai sus dimensiones
np.resize(xxx,(8,7))

array([[1, 2, 3, 4, 5, 6, 7],
       [8, 1, 2, 3, 4, 5, 6],
       [7, 8, 1, 2, 3, 4, 5],
       [6, 7, 8, 1, 2, 3, 4],
       [5, 6, 7, 8, 1, 2, 3],
       [4, 5, 6, 7, 8, 1, 2],
       [3, 4, 5, 6, 7, 8, 1],
       [2, 3, 4, 5, 6, 7, 8]])

### EJERCICIO 1
Crear un array de datos con valores entre 5 y 120
### EJERCICIO 2
Crear matriz cuadrada de 4 con valores desde 0 a 15
### EJERCICIO 3
Crear la identidad de 7*7
### EJERCICIO 4
Crear un array de 20 elementos y transformarlos en una matriz de 5*4
### EJERCICIO 5
Crear un array de 20 numeros con valores entre 0 y 5 con distancias uniformes

In [43]:
ej1=np.array(np.arange(5,121))

In [49]:
ej2=np.arange(16)
ej2.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
ej3=np.eye(7)
ej3

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [4]:
ej4=np.array(np.arange(20))
ej4.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
ej5=np.array(np.linspace(0,5,20))
ej5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## PROPIEDADES DE LOS ARRAYS
- Tamaño
- Dimension
- Tipo de dato que contiene

In [6]:
x=np.arange(12)
x=x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
x.ndim

2

In [9]:
x.shape

(3, 4)

In [10]:
x.size

12

In [11]:
x.dtype

dtype('int32')

In [12]:
x.itemsize

4

In [13]:
x.data

In [14]:
x[2]

array([ 8,  9, 10, 11])

In [21]:
x[2,1]=9
x[2,1]

9

In [23]:
x.shape=(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
x[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [26]:
y=np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
y[3:7:2]

array([3, 5])

In [28]:
ar=np.arange(10,6,-1)
ar

array([10,  9,  8,  7])

In [29]:
ar=np.arange(50)

In [30]:
ar[ar>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [33]:
cond=ar<25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [37]:
x=np.arange(50)
x[2:4]=1
x

array([ 0,  1,  1,  1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
x[13:16]=[12,15,999]
x

array([  0,   1,   1,   1,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        12,  15, 999,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

## COPIAS Y VISTAS DE ARRAYS

In [39]:
x=np.arange(10)
y=x
#ESTO NO ES UNA COPIA, SINO UNA REFERENCIA

In [41]:
y.shape=(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
z=x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
z is x

False

In [45]:
y is x

True

In [46]:
t=x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
#TENER DIFERENTES VISTAS DE UN OBJETO PERMITE
#SER MAS FLEXIBLE
t.shape=(5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
s=x[0:2,1:3]
s

array([[1, 2],
       [6, 7]])

In [52]:
s[:]=5
s

array([[5, 5],
       [5, 5]])

In [53]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [54]:
np.exp(x)

array([[1.00000000e+00, 1.48413159e+02, 1.48413159e+02, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 1.48413159e+02, 1.48413159e+02, 2.98095799e+03,
        8.10308393e+03]])

In [55]:
np.exp2(x)

array([[  1.,  32.,  32.,   8.,  16.],
       [ 32.,  32.,  32., 256., 512.]])

In [57]:
np.power(3,x)
#ARGS power (NUMAELEVAR,POTENCIA)

array([[    1,   243,   243,    27,    81],
       [  243,   243,   243,  6561, 19683]], dtype=int32)

In [58]:
np.power(x,2)

array([[ 0, 25, 25,  9, 16],
       [25, 25, 25, 64, 81]], dtype=int32)

In [60]:
np.log(x)

<ipython-input-60-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([[      -inf, 1.60943791, 1.60943791, 1.09861229, 1.38629436],
       [1.60943791, 1.60943791, 1.60943791, 2.07944154, 2.19722458]])

In [61]:
np.sum(x)
#SUMA LOS VALORES DE UN ARRAY

49

In [62]:
np.nansum(x)
#SUMA LOS VALORES DE UN ARRAY EVITANDO LOS NA'S

49

In [63]:
np.prod(x)

0

In [64]:
np.mean(x)

4.9

In [65]:
np.median(x)

5.0

In [66]:
np.std(x)

2.3430749027719964

In [67]:
np.argmin(x)
#DEVUELVE LA POSICIÓN EN LA QUE SE ENCUENTRA
#EL VALOR MÍNIMO DENTRO DEL ARREGLO

0

In [68]:
np.argmax(x)
#DEVUELVE LA POSICIÓN DEL VALOR MÁXIMO

9

In [70]:
np.percentile(x,q=0.5)

0.135

In [71]:
np.any(x)
#DEVUELVE TRUE SI ALGUNO ES 1

True

In [72]:
np.all(x)
#DEVUELVE TRUE SI TODOS SON 1

False

In [75]:
z=np.random.random((3,5))
z

array([[0.45357328, 0.98101908, 0.92559849, 0.31541179, 0.51680538],
       [0.83645381, 0.70196396, 0.24723758, 0.01416281, 0.78419836],
       [0.61554245, 0.18138725, 0.59814762, 0.64697321, 0.87682014]])

In [76]:
z.sum()

8.695295216063874

In [77]:
z.sum(axis=0)
#SUMA POR COLUMNAS

array([1.90556955, 1.86437028, 1.77098369, 0.97654782, 2.17782388])

In [79]:
z.sum(axis=1)
# SUMA POR FILAS

array([3.19240802, 2.58401652, 2.91887067])

# TEMA 1. MATRICES CON PYTHON ALGEBRA LINEAL
Vamos a crear una matriz con `numpy`

In [80]:
row=[1,2,3]
row

[1, 2, 3]

In [81]:
col=[[1],[2],[3]]
col

[[1], [2], [3]]

In [83]:
M=[[1,2,3],[4,5,6],[7,8,9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [84]:
M[1][1]

5

In [85]:
import numpy as np

In [87]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)#float
M

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [88]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
np.shape(M)

(3, 3)

In [98]:
A=np.array([[1,2],[3,4]])
print("Matriz a: "+str(A))
B=np.array([[5,6],[7,8]])
print("Matriz B: "+str(B))

Matriz a: [[1 2]
 [3 4]]
Matriz B: [[5 6]
 [7 8]]


In [93]:
A+B

array([[ 6,  8],
       [10, 12]])

In [94]:
# SI SE QUIERE MULTIPLICAR NO HAGAS
A*B
#DEBIDO AQUE LO QUE HACE ES UN PRODUCTO TENSORIAL
# ES DECIR COORDENADA POR COORDENADA, LA FORMA CORRECTA ES

array([[ 5, 12],
       [21, 32]])

In [96]:
A.dot(B)
#FORMA CORRECTA DE MULTIPLICAR MATRICES

array([[19, 22],
       [43, 50]])

In [99]:
A.trace()
#ES LA SUMA DE LOS ELEMENTOS
#DE LA DIAGONAL

5

In [100]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [102]:
np.linalg.matrix_rank(A)
#PAQUETE DE ALGEBRA LINEAL, POTENCIAS DE MATRICES,
#TIENE MUCHAS FUNCIONALIDADES DEL ALGEBRA LINEAL
#MATRIX RANK

2

In [103]:
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

In [105]:
np.linalg.det(A)
#UN DETERMINANTE TE AYUDA A SABER SI LA MATRIZ ES
#INVERTIBLE O NO

-2.0000000000000004

In [106]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [107]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## PARA ACCEDER A COLUMNAS
Tenemos que hacer lo siguiente:

In [ ]:
#CANTIDAD DE COLUMNAS
row=[1,2,3]

In [109]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
for row in M:
    print(row[0])
#SE IMPRIMEN LAS COLUMNAS

1
4
7


In [113]:
#PARA IMPRIMIR LAS FILAS
M[0]

array([1, 2, 3])